config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get 'home/top' => 'homes#top', as: 'top'

  resources :books, only: [:new, :create, :index, :edit, :show, :update, :destroy]

  resources :users, only: [:index, :edit, :show, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpeg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top]

   before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    user_path(current_user.id)
   end

  def after_sign_out_path_for(resource)
    about_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            redirect_to book_path(@book.id)
        else
            render :index
        end
    end

    def index
        @book = Book.new
        @books = Book.all
        @user = current_user
    end

    def show
        @book = Book.find(params[:id])
        @books = Book.all
        @user = @book.user
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        redirect_to books_path
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    private

    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @books = Book.all
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<h4>name<%= user.name %></h4>
<h4>introduction<%= user.introduction %></h4>

<%= link_to 'edit',edit_user_path(current_user.id) %>

<h2>New book</h2>
<%= form_with model: book do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>

  <p>Opinion</p>
  <%= f.text_area :body %><br>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/edit.html.erb
<h2>Editing book</h2>
<%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title %>
  <label for="inputBody">Opinion</label>
  <%= f.text_field :body %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'userinfo', user: @user, book: @book %>

<h1>Books</h1>

<% @books.each do |book| %>

  <p><%= link_to book.title,book_path(book.id) %></p>
  <p><%= book.body %></p>

<% end %>

app/views/books/show.html.erb
<%= render 'userinfo', user: @book.user, book: @book.user %>

<h1>Book detail</h1>

  <p><%= image_tag @book.user.get_profile_image(100,100) %></p>
  <p><%= link_to @book.user.name,user_path(@user.id) %></p>
  <p><%= link_to @book.title,book_path(@book.id) %></p>
  <p><%= @book.body %></p>

app/views/homes/about.html.erb
about

app/views/homes/top.html.erb
<h1>Welcome to Bookers !!</h1>
<p>In Bookers</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
<p><%= link_to 'Log in',new_user_session_path %></p>
<p><%= link_to 'Sigh up',new_user_registration_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <li>
        <%= link_to 'Bookers',top_path %>
      </li>

      <% if user_signed_in? %>
        <li>
          <%= link_to 'Home',user_path(current_user.id) %>
        </li>
        <li>
          <%= link_to 'Users',users_path %>
        </li>
        <li>
          <%= link_to 'Books',books_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Home' %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
    <footer>
      CopyRight Infratop.inc
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<%= render 'books/userinfo', user: @user, book: @book %>

<h1>Users</h1>

<% @users.each do |user| %>

    <p>image</p>
        <% if user.profile_image.attached? %>
        <%= image_tag user.profile_image, size: "200x200" %>
      <% else %>
        <%= image_tag 'no_image', size: "200x200" %>
      <% end %>
    <p>name</p>
    <%= user.name %>
    <p><%= link_to 'show',user_path(user.id) %></p>

<% end %>

app/views/users/show.html.erb
<%= render 'books/userinfo', user: @user, book: @book %>


<h2>Books</h2>

<% @books.each do |book| %>

  <p>Title<%= link_to book.title,book_path(book.id) %></p>
  <p>Opinion<%= book.body %></p>

<% end %>